### ISSUE TITLE
Cheating detected

### ISSUE THREAD

**Issue by MysticsV2** [Jurassic001/Auto-Bean#26]
Have friends coming to me saying there's said cheating detected. Is there a fix?

**Comment by murphilius** [comment]
same here. lmk when fixed

**Comment by Superpickl** [comment]
any update on this? i just got 14 dubious minutes
<img width="221" alt="image" src="https://github.com/Jurassic001/Auto-Bean/assets/161273269/8a655d1b-4e3d-4b69-8759-2efff8d554f4">

**Comment by murphilius** [comment]
we are so cooked tomorrow bruh

**Comment by iarchiveml** [comment]
who the hell was working on a sunday at membean lol
i'm so fucking cooked, if i was a steak i'd be congratulations

**Comment by Superpickl** [comment]
Jurassic001 , don’t fail us now! We need you!

**Comment by Superpickl** [comment]
YOOoOoo! He just fixed it!!!!!!!

**Comment by Jurassic001** [comment]
Hey guys, first of all thank you all so much for being so patient. Your feedback helps me respond to issues quickly and effectively.

I've just released a hotfix on main that worked for me, test it out and let me know if it works for you guys.

I'm sorry that some of you got dubious minutes, but thank you so much for being on "the frontlines" so to speak, and bringing it my attention so quickly.

**Comment by murphilius** [comment]
im not trying to get 0’s, so just lmk when its tested

**Comment by Superpickl** [comment]
Thank you man, your my life saver

**Comment by Jurassic001** [comment]
> is there an in depth reason as to why it was detecting it, so i can be more careful in the future?

It isn't something that the user is doing, it's just a quirk of Membean. 

You can think of the pass button as having several "layers". Each of these layers is different, but each one has the same surface level result of answering a question correctly. However, each layer leaves behind a different footprint, which essentially tells Membean which layer you are using to answer a question correctly. That's how they flag you, if you click the wrong layer.

One of these layers must be linked to the actual question answer, so that regular users can answer questions. That's the layer we want to click on. Recently, Membean has been changing which layer is the "real" one, which is what happens when everyone using this program gets flagged. I'm not sure of a way to determine which layer is real during program runtime, but I'm very open to suggestions. Right now we're clicking on the outermost layer, or the "parent" of its inner layers.


In other news, I've been told by some friends that this new patch doesn't flag them for cheating, so feel safe to try it out.

**Comment by Jurassic001** [comment]
Closing this issue because I've personally run sessions on the new patch without any issues, and I haven't heard any complaints of detection since the patch.

Again, big thanks to everyone for their quick reports and patience!
